# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmux < Formula
  desc ""
  homepage "https://github.com/corvofeng/gmux"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corvofeng/gmux/releases/download/v1.0.3/gmux_darwin_amd64.tar.gz"
      sha256 "c1db10fdf26c60dc6dd2861693caa47bdcd9ea0d2fedea5eb42511281d77ddc6"

      def install
        bin.install "gmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corvofeng/gmux/releases/download/v1.0.3/gmux_darwin_arm64.tar.gz"
      sha256 "2bb41c0588d78453e48744d4860ffbd55da19489e13c75bfd889fa99c918a518"

      def install
        bin.install "gmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/corvofeng/gmux/releases/download/v1.0.3/gmux_linux_amd64.tar.gz"
      sha256 "63512bd1b819f3edc13fb529e5a2f81982b05c59143f05171a894d72e85db00e"

      def install
        bin.install "gmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvofeng/gmux/releases/download/v1.0.3/gmux_linux_arm64.tar.gz"
      sha256 "fb9c8a9d58148728819f7377a5b16a1569f5d79546cea8b64219c056a2889480"

      def install
        bin.install "gmux"
      end
    end
  end
end
