# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemux < Formula
  desc ""
  homepage "https://github.com/corvofeng/kubemux"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corvofeng/kubemux/releases/download/v1.1.3/kubemux_darwin_amd64.tar.gz"
      sha256 "d23d01dcac14898a9682b50a161f2f9b4321d9a56a711950eae7bf3454d58350"

      def install
        bin.install "kubemux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corvofeng/kubemux/releases/download/v1.1.3/kubemux_darwin_arm64.tar.gz"
      sha256 "8052814c9adbcd2fefab4628a31e1924e080d54471b1c9622d0a03954e452fb2"

      def install
        bin.install "kubemux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/corvofeng/kubemux/releases/download/v1.1.3/kubemux_linux_amd64.tar.gz"
      sha256 "c7072fe8d3b334cd4fa3540e3120bb5a0c9ce8e65ffe0222997ca81290f0a4e6"

      def install
        bin.install "kubemux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvofeng/kubemux/releases/download/v1.1.3/kubemux_linux_arm64.tar.gz"
      sha256 "862900c2040643116ba36371a4b4d4c9e7057eb691352458f2f7f9d605383413"

      def install
        bin.install "kubemux"
      end
    end
  end
end
