# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemux < Formula
  desc ""
  homepage "https://github.com/corvofeng/kubemux"
  version "1.2.3"

  on_macos do
    on_intel do
      url "https://github.com/corvofeng/kubemux/releases/download/v1.2.3/kubemux_darwin_amd64.tar.gz"
      sha256 "d8a16095ee9ef3a58532a5f036ff14946cb7e36ecdb2d0261ceb2169441cb107"

      def install
        bin.install "kubemux"
      end
    end
    on_arm do
      url "https://github.com/corvofeng/kubemux/releases/download/v1.2.3/kubemux_darwin_arm64.tar.gz"
      sha256 "336368ee29f1da3e0ae005c0077f1ba5cdda97cdc667f567785ca0e035c117ff"

      def install
        bin.install "kubemux"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/corvofeng/kubemux/releases/download/v1.2.3/kubemux_linux_amd64.tar.gz"
        sha256 "c652414de217b3f792d7325ff2b29b23c6b4227708fd6c84d064268b598ba8bf"

        def install
          bin.install "kubemux"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/corvofeng/kubemux/releases/download/v1.2.3/kubemux_linux_arm64.tar.gz"
        sha256 "7dbb7a3b1200773d6647ed906ac5baf8b0fadad28d35a28fdd52a385ac6a9487"

        def install
          bin.install "kubemux"
        end
      end
    end
  end
end
